set(CMAKE_C_LINK_EXECUTABLE
    "\"${OXDK_LINK_EXE}\" <LINK_FLAGS> /OUT:<TARGET> <OBJECTS> <LINK_LIBRARIES>"
    CACHE STRING "" FORCE)
set(CMAKE_CXX_LINK_EXECUTABLE
    "\"${OXDK_LINK_EXE}\" <LINK_FLAGS> /OUT:<TARGET> <OBJECTS> <LINK_LIBRARIES>"
    CACHE STRING "" FORCE)

set(CMAKE_C_CREATE_STATIC_LIBRARY
    "\"${OXDK_LIB_EXE}\" /nologo /OUT:<TARGET> <OBJECTS>"
    CACHE STRING "" FORCE)
set(CMAKE_CXX_CREATE_STATIC_LIBRARY
    "\"${OXDK_LIB_EXE}\" /nologo /OUT:<TARGET> <OBJECTS>"
    CACHE STRING "" FORCE)

set(CMAKE_EXE_LINKER_FLAGS    "${_OXDK_EXE_LINKER_FLAGS}"    CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${_OXDK_SHARED_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_DEBUG    "${_OXDK_EXE_LINKER_FLAGS_DEBUG}"    CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${_OXDK_SHARED_LINKER_FLAGS_DEBUG}" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_DEBUG   "${_OXDK_C_FLAGS_DEBUG}"   CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "${_OXDK_CXX_FLAGS_DEBUG}" CACHE STRING "" FORCE)

set(CMAKE_C_STANDARD_LIBRARIES   "" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)

foreach(_oxdk_lang C CXX)
    set(CMAKE_${_oxdk_lang}_CREATE_CONSOLE_EXE "")
    set(CMAKE_${_oxdk_lang}_CREATE_WIN32_EXE   "")
    set(CMAKE_${_oxdk_lang}_USING_LINKER_DEFAULT "")
    set(CMAKE_${_oxdk_lang}_USING_LINKER_LLD     "")
endforeach()
